version: '2'
services:
  web:
    depends_on:
      - app
    build: config/deploy/nginx
    ports:
      - '80:80'
  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
  app:
    depends_on:
      - redis
    build: .
    command: node index.js
    ports:
      - '3000:3000'
    env_file:
      - .env